version: '3.9'

services:
  scrapers:
    build:
      context: ./scrapers/
    container_name: scrapers
    volumes:
      - ./scrapers:/raw/scrapers
    ports:
      - "8080:8080"
    init: true
  predictors:
    build:
      context: ./predictors/
    container_name: predictors
    volumes:
      - ./predictors:/raw/predictors
    ports:
      - "8081:8081"
    init: true